config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flats_path(@flat)
  end

  def show
    @flat = Flat.find(params[:id])
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Simple Airbnb</h1>
<%= link_to "ADD A FLAT", new_flat_path %>
<ul>
  <li>
    <% @flats.each do |flat| %>
    <%= link_to flat.name, flat_path(flat) %><br>
    <%= flat.address %><br>
    <%= flat.price_per_night %>£<br>
    <%= flat.number_of_guests %> guests<br>
    <hr>
    <% end %>
  </li>
</ul>

app/views/flats/new.html.erb
<h1>New Flat</h1>
<%= simple_form_for [@flat] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests%>
  <%= f.submit "Add New Flat", class: "btn btn-primary" %>
<% end %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>
<%= @flat.address %><br><hr>
<%= @flat.description %><br><hr>
<%= @flat.price_per_night %>£<br><hr>
<%= @flat.number_of_guests %> Guests<br><hr>
<%= link_to"Back to Home", flats_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>